#!/usr/bin/env python3
"""Regenerate writing_c_compiler gauntlet with #include resolution."""
import json
import re
from pathlib import Path

REPO_ROOT = Path("/home/wubu/wubunos")
DEPOT_DIR = REPO_ROOT / "test_gauntlet" / "depot"
SUITES_DIR = REPO_ROOT / "test_gauntlet" / "suites"

def resolve_includes(source, source_dir, depth=0):
    """Resolve #include "..." directives by inlining file contents."""
    if depth > 10:
        return source
    
    lines = source.split('\n')
    result = []
    for line in lines:
        m = re.match(r'^\s*#\s*include\s+"([^"]+)"', line)
        if m:
            inc_path = m.group(1)
            # Resolve relative to the source file's directory
            inc_file = (source_dir / inc_path).resolve()
            if inc_file.exists():
                inc_source = inc_file.read_text()
                # Recursively resolve includes in the included file
                resolved = resolve_includes(inc_source, inc_file.parent, depth + 1)
                result.append(f"/* BEGIN {inc_path} */")
                result.append(resolved)
                result.append(f"/* END {inc_path} */")
            else:
                result.append(f"/* SKIPPED {inc_path} (not found) */")
        else:
            result.append(line)
    
    return '\n'.join(result)

def generate_writing_c_compiler_full():
    """Generate gauntlet using full source files with #include resolution."""
    wcc_dir = DEPOT_DIR / "writing-c-compiler" / "upstream" / "tests"
    if not wcc_dir.exists():
        print("  writing-c-compiler not cloned, skipping")
        return

    # Load expected results
    results_file = DEPOT_DIR / "writing-c-compiler" / "upstream" / "expected_results.json"
    if not results_file.exists():
        print("  expected_results.json not found, skipping")
        return

    expected_results = json.loads(results_file.read_text())

    tests = []
    for chapter_dir in sorted(wcc_dir.iterdir()):
        if not chapter_dir.is_dir():
            continue
        valid_dir = chapter_dir / "valid"
        if not valid_dir.exists():
            continue

        # Recursively find all .c files in valid/
        for test_file in sorted(valid_dir.rglob("*.c")):
            # Key format: chapter_XX/valid/name.c (or chapter_XX/valid/subdir/name.c)
            relative = test_file.relative_to(wcc_dir)
            test_key = str(relative)
            
            result = expected_results.get(test_key)
            if result is None:
                continue

            source = test_file.read_text()
            if len(source) > 65536:
                continue

            # Check if file has main()
            if "int main(" not in source and "void main(" not in source:
                continue

            # Resolve #include directives
            source = resolve_includes(source, test_file.parent)

            # result is {"return_code": N}
            return_code = result.get("return_code", 0)
            tests.append({
                "name": f"wcc_{test_key.replace('/', '_').replace('.c', '')}",
                "source": source,
                "expected_return": return_code,
            })

    # Write the gauntlet file
    output_path = SUITES_DIR / "gauntlet_writing_c_compiler_full.c"
    with open(output_path, "w") as f:
        f.write("/* Auto-generated by regenerate_wcc.py — full source + #include resolution */\n")
        f.write(f"/* Tests: {len(tests)} */\n\n")
        f.write('#include "wubu_test_gauntlet.h"\n\n')
        f.write("const test_entry_t gauntlet_writing_c_compiler_full_tests[] = {\n")

        for i, t in enumerate(tests):
            src = t["source"].replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
            expected = t.get("expected_return", 0)
            f.write(f'    {{"{t["name"]}", "{src}", {expected}, TEST_CAT_INTEGER, 0, 100}}')
            if i < len(tests) - 1:
                f.write(",")
            f.write("\n")

        f.write("};\n\n")
        f.write(f"const uint32_t gauntlet_writing_c_compiler_full_test_count = {len(tests)};\n")

    print(f"  Generated gauntlet_writing_c_compiler_full: {len(tests)} tests")
    return len(tests)

if __name__ == "__main__":
    generate_writing_c_compiler_full()
